### ISSUE TITLE
숏폼 UI 구현

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#14]
**Description**
숏폼 UI 구현 & navigation UI 변경

**TODO**
- [x] exoplayer 라이브러리 import
- [x] navigation UI 변경
- [x] 숏폼 메인 UI 구현
- [x] 숏폼 상세 UI 구현
- [x] 숏폼 상품 recyclerview 구현

**ETC**
