### ISSUE TITLE
로그인/회원가입 API 연동

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#15]
**Description**
로그인 기획변경 대응 및 로그인/회원가입 API 연결

**TODO**
- [x] 로그인 화면 수정 
- [x] 닉네임 API 연동
- [x] 회원가입 API 연동

**ETC**
