### ISSUE TITLE
스플래시/온보딩 수정

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#18]
**Description**
스플래시/온보딩 UI 수정

**TODO**
- [x] 스플래시 UI 로고 변경
- [x] 온보딩 UI 수정
- [x] 닉네임 UI 수정

**ETC**
