### ISSUE TITLE
Home 화면 UI

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#3]
**Description**
Home 화면 UI 구현

**TODO**
- [x] 스플래시 화면 구현
- [x] bottom navigation 구현
- [x] 식재료 등록 UI
- [x] 홈 화면 UI
- [x] 냉장고 UI

**ETC**
