### ISSUE TITLE
로그아웃 API 연결 수정

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#33]
**Description**
로그아웃 API 연결 수정

**TODO**
- [x] 로그아웃 API 수정사항 반영
- [x]  splash api 제거, splash activity 추가
- [x] refresh token API 연결
- [x] 로그인 UI bug 수정
- [x] 회원가입 완료 화면 삭제

**ETC**
