### ISSUE TITLE
레시피 UI 누락된 기능 구현

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#35]
**Description**
레시피 UI 누락 기능 구현

**TODO**
- [x] 레시피 차트 추가 
- [x] 레시피 메인 버튼 chip으로 변경
- [x] 레시피 검색 버튼 chip으로 변경
- [x] 숏츠 검색 버튼 chip으로 변경
- [x] ratingbar 수정

**ETC**
