### ISSUE TITLE
레시피 작성 UI 수정

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#38]
**Description**
레시피 작성 UI 수정

**TODO**
- [x] 디자인 반영
- [x] 썸네일 이미지 추가 구현
- [x] 조리단계 입력 edittext 줄바꿈 처리
- [x] 재료 갯수 등록 다이얼로그 생성
- [x] 재료 양 등록 다이얼로그 생성
- [x] 재료 adapter 연결
- [x] 조리단계 삭제 리스너 구현
- [x] 조리단계 이동 리스너 구현
- [x] 조리단계 이미지 삭제 기능 구현
- [x] 커스텀 스낵바 추가
- [x] 게시버튼 클릭 시 레시피 작성 fragment 호출

**ETC**
