### ISSUE TITLE
댓글 API 

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#49]
**Description**
댓글 API 연결 & 숏츠 관련 기능 추가구현

**TODO**
- [x] 레시피 댓글 API
- [x] 숏츠 댓글 신고 API
- [x] 업로드 뷰 백그라운드 처리
- [x] 쿠팡 화면 이동 기능 구현
- [x] 이용약관 파일 연결기능 추가
- [x] 메인화면 이용약관 파일 다운로드 기능 추가

**ETC**
