### ISSUE TITLE
온보딩 UI

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#6]
**Description**
온보딩 - 스플래시 화면 / 앱 컬러 변경

**TODO**
- [x] 스플래시 화면 UI 구현
- [x] app icon 추가
- [x] bottom navigation color 수정
- [x] 상태바 색상 변경

**ETC**
