### ISSUE TITLE
v1.0.2 버그 수정

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#65]
**Description**
v1.0.2 버그 수정 & 기능 개선

**TODO**
- [x] 검색 후 이동 기능 연결
- [x] 저장레시피 / 작성레시피 이동 기능 연결
- [x] 최근 본 페이지 / 최근 본 숏폼 이동 기능 연결

**ETC**
