### ISSUE TITLE
v1.0.4 수정사항

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#68]
**Describe the bug**
svg 파일 깨짐 & 누락된 api 연결

**Todo**
- [x] 레시피 api 연결
- [x] svg 파일 깨짐 구현
- [x] 구글 svg 추가
