### ISSUE TITLE
v1.0.5 개선사항

### ISSUE THREAD

**Issue by ymym1024** [Central-MakeUs/Re_Cipe_Android#70]
**Description**
v1.0.5 개선사항

**TODO**
- [x] 레시피 순서 정확하게
- [x] mypage logo 잘림 해결
- [x] 레시피 상세페이지에서 저장 시 앱 ANR 발생
- [x] 폰트 prentend 적용
- [x] 레시피 상품 이름 길이 고정 값 변경
- [x] 숏폼 문자열 길이 bug fix 
- [x] 레시피 리뷰 최신순 베스트 순

**ETC**
